name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
            xcode-version: '15.0'

      - name: Install dependencies
        run: |
          cd RailMap

      - name: Build and run tests
        run: |
          xcodebuild clean build analyze -scheme RailMap -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
          
